config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  get 'store', to: 'store#index', as: 'store_index' 
  get 'admin', to: 'admin#index'
  get 'contact', to: 'home#contact'
  
  post 'request_contact', to: 'home#request_contact'

  resources :users, except: [:show]
  resources :orders, except: [:edit]
  resources :line_items, except: [:edit, :new, :show]
  resources :carts, except: [:edit, :new]
  resources :phones do
    get :who_bought, on: :member
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
end

app/models/phone.rb
class Phone < ApplicationRecord
    # Defining the relationship between phones and line items & orders
    # A phone can be part of many line items
    # A phone can be part of many orders
    has_many :line_items
    has_many :orders, through: :line_items
    # A phone is not destroyed if it is part of a line item
    before_destroy :ensure_not_referenced_by_any_line_item

    # Validates all the attributes to be present when making the phone
    validates :brand, :model, :size, :colour, :specifications, :price, :image_url, presence: true
    # Validates the brand name to be maximum of 15 characters, error message is show if it is too long
    validates :brand, length: { maximum: 15, too_long: "Maximum allowed characters is %{count}" }
    # Validates the model name to be maximum of 250 characters, error message is show if it is too long
    validates :model, length: { maximum: 250, too_long: "Maximum allowed characters is %{count}" }
    # Validates the colour to be maximum of 50 characters, error message is show if it is too long
    validates :colour, length: { maximum: 50, too_long: "Maximum allowed characters is %{count}" }
    # Validates the pice to be a number and greater than or equal to 1 pence. Also maximum length is 9
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }, length: { maximum: 9}
    # Validates the image url. Allows the url to be blank so a product can be without an image.
    # Validates the format of the image to have gif or jpg or png.
    validates :image_url , allow_blank: true , format: { with: %r{\.(gif|jpg|png)\Z}i , message: 'must be an image URL for JPG, PNG, or GIF image.'}
    
    # Private method that stops a phone from being deleted, when its part of a line items
    private
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line Items present')
        throw :abort
      end
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # Index action lists all the phones for the admin to see
  def index
    @phones = Phone.all
  end

  # Action to show individual phones information
  def show
  end

  # Action to create an object of a phone
  def new
    @phone = Phone.new
  end

  # Action to let the admin edit the phone
  def edit
  end

  # Action to create the phone using the valid parameters provided 
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      # Notie the admin when it is successfuly created and then render the show page
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was created.' }
        format.json { render :show, status: :created, location: @phone }
      # Notices the user about the errors occured while creating the phonw 
      else
        puts @phone.errors.full_messages
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action to update the phone as an admin
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was updated.' }
        format.json { render :show, status: :ok, location: @phone }
        @phones = Phone.all
        ActionCable.server.broadcast 'phones',
          html: render_to_string('store/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action to destroy the phone as an admin
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was destroyed.' }
      format.json { head :no_content }
    end
  end

# Action to check to see if a request is stale
  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  # Private methods to set the phone and white list the parameters
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    def phone_params
      params.require(:phone).permit(:brand, :model, :size, :colour, :specifications, :image_url, :price)
    end

  
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<div class="default_form">
  <%= form_with(model: phone, local: true) do |form| %>
    <% if phone.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(phone.errors.count, "error") %><%= t('.error') %></h2>

        <ul>
        <% phone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :brand %>
      <%= form.text_field :brand %>
    </div>

    <div class="field">
      <%= form.label :model %>
      <%= form.text_field :model %>
    </div>

    <div class="field">
      <%= form.label :size %>
      <%= form.text_field :size %>
    </div>

    <div class="field">
      <%= form.label :colour %>
      <%= form.text_field :colour %>
    </div>

    <div class="field">
      <%= form.label :specifications %>
      <%= form.text_area :specifications %>
    </div>

    <div class="field">
      <%= form.label :image_url %>
      <%= form.text_field :image_url %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/phones/edit.html.erb
<% content_for(:html_title) { 'Edit Phone - Pro Phones' } %>
<h1><%= t('.title') %></h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Show', @phone, {class: "default_btn"} %> |
<%= link_to 'Back', phones_path, {class: "default_btn"} %>

app/views/phones/index.html.erb
<% content_for(:html_title) { 'Phones - Pro Phones' } %>
<% if notice %>
  <aside id= "notice" > <%= notice %> </aside>
<% end %>

<h1><%= t('.title') %></h1>

<table>
  <tfoot>
    <tr>
      <td colspan= "3" >
        <%= link_to 'New phone' , new_phone_path, {class: "default_btn"} %>
      </td>
    </tr>
  </tfoot>

<tbody>
  <% @phones.each do |phone| %>
      
    <td class= "image" >
      <%= image_tag(phone.image_url, class: 'list_image' ) %>
    </td>
    
    <td class= "specifications" >
      <h2> <%= phone.brand %> <%= phone.model %> </h2>
      <p> <%= strip_tags(phone.specifications) %> </p>
    </td>
    
    <td class= "actions" >
      <ul>
        <li> <%= link_to 'Show' , phone, {class: "default_btn sed_btn"} %> </li>
        <li> <%= link_to 'Edit' , edit_phone_path(phone), {class: "default_btn sed_btn"} %> </li>
        <li> <%= link_to 'Destroy' , phone, method: :delete , data: { confirm: 'Are you sure?' }, class:"default_btn sed_btn" %>
        </li>
      </ul>
    </td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/phones/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<% content_for(:html_title) { 'Phone Info - Pro Phones' } %>
<h1><%= t('.title') %></h1>
<p>
  <strong><%= t('.brand') %></strong>
  <%= @phone.brand %>
</p>

<p>
  <strong><%= t('.model') %></strong>
  <%= @phone.model %>
</p>

<p>
  <strong><%= t('.size') %></strong>
  <%= @phone.size %>
</p>

<p>
  <strong><%= t('.colour') %></strong>
  <%= @phone.colour %>
</p>

<p>
  <strong><%= t('.specs') %></strong>
  <%= @phone.specifications %>
</p>

<p>
  <strong><%= t('.img') %></strong>
  <%= @phone.image_url %>
</p>

<p>
  <strong><%= t('.price') %></strong>
  <%= @phone.price %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone), {class: "default_btn"} %> |
<%= link_to 'Back', phones_path, {class: "default_btn"} %>