config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  get 'store', to: 'store#index', as: 'store_index' 
  get 'admin', to: 'admin#index'
  get 'contact', to: 'home#contact'
  
  post 'request_contact', to: 'home#request_contact'

  resources :users, except: [:show]
  resources :orders, except: [:edit]
  resources :line_items, except: [:edit, :new, :show]
  resources :carts, except: [:edit, :new]
  resources :phones do
    get :who_bought, on: :member
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
end

app/views/admin/index.html.erb
<% content_for(:html_title) { 'Admin - Pro Phones' } %>

<h1><%= t('.title') %></h1>
<h3><%= t('.total') %> <%= Time.now.to_formatted_s(:long_ordinal) %> is <%= @total_orders %>.</h3><br>

<table class = "admin_table">
    <tr>
        <th><h3><strong><%= t('.phones') %><strong></h3></th>
        <th><%= link_to 'Phones', phones_path, {class: "default_btn admin_btn"} %></th>
    </tr>
    <tr>
        <th><h3><strong><%= t('.orders') %></strong></h3></th>
        <th><%= link_to 'Orders', orders_path, {class: "default_btn admin_btn"} %></th>
    </tr>
    <tr>
        <th><h3><strong><%= t('.users') %><strong></h3></th>
        <th><%= link_to 'Users', users_path, {class: "default_btn admin_btn"} %></th>
    </tr>
    <tr>
        <th><h3><strong><%= t('.logout') %><strong></h3></th>
        <th><%= button_to 'Logout', logout_path, method: :delete, data: { confirm: "Are you sure?" }, class: "default_btn admin_btn" %></th>
    </tr>
</table>