config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  get 'store', to: 'store#index', as: 'store_index' 
  get 'admin', to: 'admin#index'
  get 'contact', to: 'home#contact'
  
  post 'request_contact', to: 'home#request_contact'

  resources :users, except: [:show]
  resources :orders, except: [:edit]
  resources :line_items, except: [:edit, :new, :show]
  resources :carts, except: [:edit, :new]
  resources :phones do
    get :who_bought, on: :member
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
end

app/models/cart.rb
class Cart < ApplicationRecord
    # Defining the relationship between carts and line items
    # A cart can have many line items
    # When a cart is destroyed so does all the line items associated with it
    has_many :line_items, dependent: :destroy

    # Adds a phone to the table by finding the phone id 
    def add_phone(phone)
        current_item = line_items.find_by(phone_id: phone.id)
        # If the specific id already exists, increaese the quantity by one
        if current_item
          current_item.quantity += 1
        # else build a new one
        else
          current_item = line_items.build(phone_id: phone.id)
        end
        current_item
    end

    # Method to get the total price line items to display in the cart
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # Gives a normal user access to only create, update and destroy actions of the cart
  skip_before_action :authorize, only: [:create, :update, :destroy]

  # The index page of carts which shows all the available carts
  def index
    @carts = Cart.all
  end

  # Show page for individual carts
  def show
  end

  # Action to create an object of a cart
  def new
    @cart = Cart.new
  end

  # Create action which creates a new cart when the user adds a product to the cart
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        # Notice to let the user know the cart was created
        format.html { redirect_to @cart, notice: 'Cart was created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        # Error message to display when the cart is not created
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action to update the cart
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action to destroy the cart as an admin
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url,
        notice: 'Your cart is empty' }
      format.json { head :no_content }
    end
  end

  
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Method to allow white listed parameters 
    def cart_params
      params.fetch(:cart, {})
    end

    # Error Message when trying to access invalid cart
    def invalid_cart
      logger.error "Cart #{params[:id]} doesn't exist"
      redirect_to store_index_url, notice: 'Cart is invalid'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<article>
  <% if notice %>
    <aside id="notice"><%= notice %></aside>
  <% end %>

  <h2><%= t('.title') %></h2>
  <table>

    <%= render(cart.line_items) %>
    <tfoot>
      <tr>
        <th colspan="2"><%= t('.total') %></th>
        <td class="price"><%= number_to_currency(cart.total_price, :unit =>"£") %></td>
      </tr>
    </tfoot>
  </table>
  <div class="actions">
    <br><%= button_to 'Checkout', new_order_path, method: :get, class: "checkout"%><br>
    <%= button_to 'Empty cart', cart, method: :delete, data: { confirm: 'Do you want to empty the cart?' } %>
  </div>
</article>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %><%= t('.error') %></h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.table_head') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td class = "carts_id"><%= cart.id %></td>
        <td><%= link_to 'Show', cart, class: "default_btn" %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "default_btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/carts/show.html.erb
<%= render @cart %>
<%= link_to 'Back', carts_path, class: "default_btn" %>